name: Scheduled Pipeline

# Trigger this workflow based on a schedule
on:
  schedule:
    # Runs at 3:00 AM UTC every day
    - cron: "0 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 11

      - name: Build and Test
        run: mvn test
